name: Java CI with Gradle

on:
  push:
  pull_request:

permissions:
  contents: read
  checks: write
  statuses: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()  # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
